version: "3.4"
services:
  flask_app:
    build: .
    image: fashion-campus-be
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
  
  web:
    image: dallas18/startup-campus-fe:latest
    ports:
      - 3000:3000
    depends_on:
      - flask_app

  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - db-volume:/var/lib/postgresql/data

  celery_worker:
    build: .
    image: fashion-campus-worker
    command: celery -A app.main.celery worker --loglevel=INFO --uid=nobody --gid=nogroup
    env_file:
      - .env
    depends_on:
      - flask_app
      - redis_worker
  
  redis_worker:
      image: redis:7
      ports:
      - 6379:6379
      environment:
      - REDIS_PASSWORD=redisworker101

  image_prediction:
    image: dallas18/image-prediction-ai:latest
    ports:
      - 5050:5050

volumes:
   db-volume: