version: "3.4"
services:
  flask_app:
    build: .
    image: fashion-campus-be
    ports:
      - 5000:5000
    env_file:
      - .env
  
  web:
    image: dallas18/startup-campus-fe-local:latest
    ports:
      - 3000:3000
    depends_on:
      - flask_app

  celery_worker:
    build: .
    image: fashion-campus-worker
    command: celery -A app.main.celery worker --loglevel=INFO --uid=nobody --gid=nogroup
    env_file:
      - .env
    depends_on:
      - flask_app
      - broker
  
  broker:
    image: rabbitmq:3.11.4
    environment:
    - RABBITMQ_DEFAULT_USER=dallas

  image_prediction:
    image: dallas18/image-prediction-ai:latest
    ports:
      - 5050:5050