"""empty message

Revision ID: 5cb9ae3a9996
Revises: 35a02f8cc1f9
Create Date: 2022-10-31 19:58:50.969319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5cb9ae3a9996'
down_revision = '35a02f8cc1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_detail', sa.Column('price', sa.Float(), nullable=False))
    op.drop_constraint('product_category_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_category_id_fkey', 'product', 'category', ['category_id'], ['id'])
    op.drop_column('order_detail', 'price')
    # ### end Alembic commands ###
