"""empty message

Revision ID: bf51a08822eb
Revises: 21f1aba57d44
Create Date: 2022-11-25 06:25:11.687623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf51a08822eb'
down_revision = '21f1aba57d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('deleted', sa.Enum('0', '1', name='deleted'), server_default='0', nullable=False))
    op.add_column('product', sa.Column('deleted', sa.Enum('0', '1', name='deleted'), server_default='0', nullable=False))
    op.drop_column('product', 'is_deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_deleted', postgresql.ENUM('0', '1', name='isdelete'), server_default=sa.text("'0'::isdelete"), autoincrement=False, nullable=False))
    op.drop_column('product', 'deleted')
    op.drop_column('category', 'deleted')
    # ### end Alembic commands ###
