"""empty message

Revision ID: db75cc37ff28
Revises: db4fd81c75a3
Create Date: 2022-11-26 13:05:47.200244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db75cc37ff28'
down_revision = 'db4fd81c75a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', postgresql.ENUM('0', '1', name='admin'), server_default=sa.text("'0'::admin"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
